/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe демона (без auth) */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Версия демона */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список проектов */
        get: operations["listProjects"];
        put?: never;
        /** Зарегистрировать проект */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проект с активными ранами и счётчиком открытых гейтов */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Удалить проект КАСКАДНО (раны, стадии, события, гейты, заметки) */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Обновить ide_command / default_branch */
        patch: operations["patchProject"];
        trace?: never;
    };
    "/projects/{id}/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пайплайны проекта (+ глобальные) */
        get: operations["listProjectPipelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Версия пайплайна со списком всех версий */
        get: operations["getPipeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать пайплайн (первая версия) */
        post: operations["createPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт пайплайна из YAML (T-21) */
        post: operations["importPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все версии пайплайна */
        get: operations["listPipelineVersions"];
        put?: never;
        /** Новая версия пайплайна (правка = новая версия, T-21) */
        post: operations["createPipelineVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline-versions/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Конкретная версия пайплайна */
        get: operations["getPipelineVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline-versions/{vid}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экспорт версии в YAML (T-21) */
        get: operations["exportPipelineVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список ранов с фильтрами */
        get: operations["listRuns"];
        put?: never;
        /** Создать ран (идемпотентно, D-12) */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Полный срез рана (стадии, гейты, артефакты) */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Остановить ран (идемпотентно, D-14) */
        post: operations["stopRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ручной рестарт failed/interrupted рана */
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue note к ближайшему событию рана (D-22) */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** REST-доступ к журналу событий рана */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/artifacts/{artifactId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Содержимое файла артефакта (F-02, fix-task-4). Путь читается только
         *     из записи БД и обязан оставаться внутри каталога рана (run_dir);
         *     чужой/несуществующий артефакт, выход за run_dir и отсутствующий файл
         *     → 404. Файл больше cap'а (5 МБ) → 413 (фронт предлагает скачать).
         */
        get: operations["getArtifactContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Метрики рана per stage + итоги (D-51, T-24) */
        get: operations["getRunMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/metrics.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Экспорт метрик рана в CSV (T-24) */
        get: operations["getRunMetricsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Агрегированные метрики проекта за период (T-24) */
        get: operations["getProjectMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Резолв гейта (идемпотентно; повтор → 200 + already_resolved) */
        post: operations["resolveGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stages/{id}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrupt & Steer (D-22) — прервать этап и резюмить с сообщением */
        post: operations["interruptStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Привязка TG-чата по коду из /start (T-19)
         * @description Пользователь отправляет боту /start → бот показывает 6-значный код →
         *     код вводится в UI → chat_id попадает в whitelist (tg_chats).
         *     Код одноразовый: успешная привязка его погашает.
         */
        post: operations["pairTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Настройки демона (экран настроек UI) */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Настройки TG-бота (токен валидируется через getMe, hot-apply адаптера) */
        put: operations["putTelegramSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/supervisor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Параметры supervisor (watchdog, пул процессов; hot-apply) */
        put: operations["putSupervisorSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fs/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Листинг подкаталогов (выбор папки проекта в браузерном UI, T-16) */
        get: operations["fsBrowse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список уроков (D-52, T-29) */
        get: operations["listLessons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Урок с содержимым файла */
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Смена статуса урока (confirm/reject из UI) */
        patch: operations["patchLesson"];
        trace?: never;
    };
    "/memory/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дерево vendor-памяти (глобальная + по проектам), T-23 */
        get: operations["memoryTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Содержимое файла памяти */
        get: operations["memoryReadFile"];
        /** Ручная правка файла памяти (T-23) */
        put: operations["memoryWriteFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История изменений файла глобальной памяти (git log) */
        get: operations["memoryHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Промоушн записи локальной памяти в глобальную (T-23) */
        post: operations["memoryPromote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket-поток событий журнала (D-04)
         * @description Upgrade в WebSocket. Протокол: догон событиями с id > last_event_id,
         *     сообщение `synced` (граница replay/live), затем live-поток Event'ов.
         *     Медленный клиент отключается (close 1001, "resync required") и
         *     переподключается с последним полученным last_event_id.
         */
        get: operations["eventsWs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description доменный код: not_found, invalid_transition, run_locked,
             *     gate_already_resolved, duplicate, draining, validation, internal
             */
            code: string;
            message: string;
            /**
             * @description контекст ошибки: dirty_checkout → {files: string[]};
             *     run_locked → {branch: string, run_id: string} (F-02)
             */
            details?: {
                [key: string]: unknown;
            };
        };
        VersionInfo: {
            version: string;
            /** @description доступные harness-адаптеры (exec.LookPath при старте, T-06) */
            harnesses?: string[];
        };
        Project: {
            /** Format: int64 */
            id: number;
            path: string;
            name: string;
            default_branch: string;
            ide_command: string;
            /**
             * @description дефолт notify_tg для новых ранов проекта (T-16)
             * @default true
             */
            notify_tg_default: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateProjectRequest: {
            path: string;
            name: string;
            default_branch?: string;
            ide_command?: string;
        };
        PatchProjectRequest: {
            default_branch?: string;
            ide_command?: string;
            notify_tg_default?: boolean;
        };
        ProjectDetail: components["schemas"]["Project"] & {
            active_runs: components["schemas"]["Run"][];
            /** @description открытые гейты по всем активным ранам проекта */
            open_gates: number;
        };
        Pipeline: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description NULL = глобальный пайплайн
             */
            project_id: number | null;
            name: string;
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            parent_version_id?: number | null;
            spec_json: string;
            /** Format: date-time */
            created_at: string;
        };
        PipelineDetail: components["schemas"]["Pipeline"] & {
            versions: components["schemas"]["Pipeline"][];
        };
        StageMetrics: {
            /** Format: int64 */
            stage_id: number;
            stage_key: string;
            /** Format: int64 */
            iteration: number;
            state: components["schemas"]["StageState"];
            /**
             * Format: int64
             * @description 0 = harness не сообщил usage (показывать «—»)
             */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            /** @description finished_at - started_at; null если не завершена */
            duration_sec?: number | null;
            /** Format: int64 */
            resume_count: number;
            /** Format: int64 */
            exit_code?: number | null;
        };
        RunMetrics: {
            run_id: string;
            stages: components["schemas"]["StageMetrics"][];
            totals: {
                /** Format: int64 */
                tokens_in: number;
                /** Format: int64 */
                tokens_out: number;
                duration_sec?: number | null;
                stages_count: number;
            };
            /** @description суммарное ожидание гейтов (производное событий, не хранится) */
            gate_wait_seconds: number;
        };
        ProjectMetrics: {
            /** Format: int64 */
            project_id: number;
            period: string;
            runs_total: number;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            total_duration_sec?: number;
            /** @description число ранов по состояниям */
            by_state: {
                [key: string]: number;
            };
        };
        Settings: {
            telegram: components["schemas"]["TelegramSettings"];
            supervisor: components["schemas"]["SupervisorSettings"];
        };
        TelegramSettings: {
            enabled: boolean;
            has_token: boolean;
            /** @description первые/последние символы, полный токен не отдаётся */
            token_masked?: string;
            /** @description из getMe при валидном токене */
            bot_username?: string | null;
        };
        TelegramSettingsPut: {
            enabled: boolean;
            /** @description пусто = оставить текущий; валидация через getMe */
            token?: string;
        };
        SupervisorSettings: {
            stall_timeout_sec: number;
            stage_timeout_min: number;
            max_parallel: number;
            /** Format: int64 */
            max_auto_resumes: number;
        };
        SupervisorSettingsPut: {
            stall_timeout_sec?: number;
            stage_timeout_min?: number;
            max_parallel?: number;
            /** Format: int64 */
            max_auto_resumes?: number;
        };
        FsBrowseResult: {
            path: string;
            parent?: string | null;
            dirs: {
                name: string;
                path: string;
                /** @description есть .git — подсказка «это проект» */
                is_git_repo: boolean;
            }[];
        };
        Lesson: {
            id: string;
            title: string;
            /** @enum {string} */
            scope: "global" | "project";
            /** @enum {string} */
            status: "proposed" | "confirmed" | "rejected" | "superseded";
            /** Format: int64 */
            project_id?: number | null;
            path: string;
            run_id?: string | null;
            stage_key?: string;
            /** Format: int64 */
            applied_count?: number;
            /** Format: int64 */
            relapse_count?: number;
            /** Format: date-time */
            created_at: string;
        };
        LessonDetail: components["schemas"]["Lesson"] & {
            content: string;
        };
        MemoryFileEntry: {
            path: string;
            vendor: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            updated_at: string;
        };
        MemoryTree: {
            global: components["schemas"]["MemoryFileEntry"][];
            projects: {
                /** Format: int64 */
                project_id: number;
                project_name: string;
                files: components["schemas"]["MemoryFileEntry"][];
            }[];
        };
        MemoryFileContent: {
            vendor: string;
            scope: string;
            content: string;
        };
        MemoryWriteFileRequest: {
            /** @enum {string} */
            scope: "global" | "project";
            vendor: string;
            content: string;
            /** Format: int64 */
            project_id?: number | null;
        };
        MemoryHistoryEntry: {
            hash: string;
            date: string;
            message: string;
        };
        MemoryPromoteRequest: {
            vendor: string;
            /** Format: int64 */
            project_id: number;
        };
        /** @enum {string} */
        RunState: "draft" | "running" | "waiting_gate" | "succeeded" | "failed" | "stopped";
        /** @enum {string} */
        StageState: "pending" | "running" | "succeeded" | "failed" | "interrupted" | "skipped";
        /** @enum {string} */
        GateKind: "plan_approval" | "question" | "escalation" | "final_review" | "lesson_review";
        /** @enum {string} */
        GateState: "open" | "answered" | "approved" | "rejected" | "expired";
        Run: {
            id: string;
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            pipeline_version_id: number;
            task_text: string;
            base_branch: string;
            branch: string;
            state: components["schemas"]["RunState"];
            /** Format: int64 */
            depth: number;
            notify_tg: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        CreatePipelineRequest: {
            name: string;
            /**
             * Format: int64
             * @description NULL = глобальный пайплайн
             */
            project_id?: number | null;
            spec_json: string;
        };
        CreatePipelineVersionRequest: {
            spec_json: string;
        };
        ImportPipelineRequest: {
            /** @description пайплайн в YAML-формате T-21 */
            yaml: string;
            /**
             * @description new — всегда новый пайплайн; version — новая версия
             *     существующего по имени; fail — ошибка при совпадении имени
             * @default new
             * @enum {string}
             */
            on_conflict: "new" | "version" | "fail";
        };
        CreateRunRequest: {
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            pipeline_version_id: number;
            task_text: string;
            /** @description не указана — default_branch проекта */
            base_branch?: string;
            /** @description не указана — glamor/<slug> от base (D-31) */
            branch?: string;
            /**
             * Format: int64
             * @default 0
             */
            depth: number;
            /** @default true */
            notify_tg: boolean;
            /**
             * @description override грязного чекаuta в preflight (D-34, T-10)
             * @default false
             */
            force: boolean;
        };
        Stage: {
            /** Format: int64 */
            id: number;
            run_id: string;
            stage_key: string;
            /** Format: int64 */
            iteration: number;
            state: components["schemas"]["StageState"];
            harness: string;
            session_id?: string | null;
            /** Format: int64 */
            pid?: number | null;
            /** Format: int64 */
            exit_code?: number | null;
            stop_requested_by?: string | null;
            /** Format: int64 */
            resume_count: number;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            error?: string | null;
        };
        Gate: {
            id: string;
            run_id: string;
            /** Format: int64 */
            stage_id?: number | null;
            kind: components["schemas"]["GateKind"];
            question: string;
            context_json?: string;
            state: components["schemas"]["GateState"];
            answer?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
        };
        ResolveGateRequest: {
            /** @enum {string} */
            action: "approve" | "reject" | "answer" | "comment";
            text?: string;
        };
        ResolveGateResponse: {
            gate: components["schemas"]["Gate"];
            already_resolved: boolean;
        };
        Artifact: {
            /** Format: int64 */
            id: number;
            run_id: string;
            /** Format: int64 */
            stage_id?: number | null;
            path: string;
            kind: string;
            /** Format: date-time */
            created_at: string;
        };
        Note: {
            /** Format: int64 */
            id: number;
            run_id: string;
            /** Format: int64 */
            stage_id?: number | null;
            text: string;
            /** @enum {string} */
            kind?: "note" | "steer";
            consumed: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateNoteRequest: {
            text: string;
        };
        InterruptStageRequest: {
            /** @description steer-сообщение — сессия резюмится с ним (D-22) */
            message: string;
        };
        RunDetail: components["schemas"]["Run"] & {
            stages: components["schemas"]["Stage"][];
            gates: components["schemas"]["Gate"][];
            artifacts: components["schemas"]["Artifact"][];
            notes: components["schemas"]["Note"][];
        };
        /**
         * @description Событие журнала (D-11). Приходит по WS (/ws) и возвращается Replay-API.
         *     kind-пространства: run.*, stage.*, gate.*, stream.*, notify.*.
         */
        Event: {
            /**
             * Format: int64
             * @description монотонный id журнала (AUTOINCREMENT)
             */
            id: number;
            /** @description uuid рана; "*" зарезервировано для подписки «все раны» */
            run_id: string;
            /** Format: int64 */
            stage_id?: number | null;
            /** Format: date-time */
            ts: string;
            kind: components["schemas"]["EventKind"];
            payload: components["schemas"]["EventPayload"];
        };
        PairTelegramRequest: {
            /** @description 6-значный код, выданный ботом на /start */
            code: string;
        };
        PairTelegramResponse: {
            /**
             * Format: int64
             * @description привязанный чат (добавлен в whitelist)
             */
            chat_id: number;
        };
        /** @enum {string} */
        EventKind: "run.created" | "run.state_changed" | "run.branch_mismatch" | "stage.state_changed" | "stage.queued" | "stage.interrupted" | "stage.resumed" | "gate.opened" | "gate.resolved" | "stream.thinking" | "stream.text" | "stream.tool_call" | "stream.tool_result" | "stream.usage" | "stream.error" | "stream.raw" | "system";
        /**
         * @description Полиморфный payload события (детерминирован kind'ом события):
         *     - run.created → RunCreatedPayload
         *     - run.state_changed / stage.state_changed → StateChangedPayload
         *     - gate.opened / gate.resolved → GatePayload
         *     - stream.thinking / stream.text / stream.raw → StreamTextPayload
         *     - stream.tool_call / stream.tool_result → StreamToolPayload
         *     - stream.usage → StreamUsagePayload
         *     - stream.error → StreamErrorPayload
         */
        EventPayload: {
            [key: string]: unknown;
        };
        /**
         * @description run.created (F-01, fix-task-4) — сериализованный объект рана в момент
         *     создания (состояние draft); поля совпадают со схемой Run. Пишется в
         *     той же транзакции, что и создание рана (D-11); повтор по
         *     Idempotency-Key второго события не порождает (D-12).
         */
        RunCreatedPayload: {
            id: string;
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            pipeline_version_id: number;
            task_text: string;
            base_branch?: string;
            branch: string;
            state: components["schemas"]["RunState"];
            /** Format: int64 */
            depth?: number;
            notify_tg?: boolean;
            /** Format: date-time */
            created_at: string;
        };
        StateChangedPayload: {
            /** @description пусто при создании сущности */
            from?: string;
            to: string;
        };
        /**
         * @description gate.opened — сериализованный объект гейта; gate.resolved —
         *     gate_id + resolution + answer.
         */
        GatePayload: {
            gate_id?: string;
            kind?: components["schemas"]["GateKind"];
            question?: string;
            /** @enum {string} */
            resolution?: "answered" | "approved" | "rejected" | "expired";
            answer?: string | null;
        };
        StreamTextPayload: {
            text: string;
        };
        StreamToolPayload: {
            tool?: string;
            call_id?: string;
            input?: {
                [key: string]: unknown;
            };
            output?: string;
            is_error?: boolean;
        };
        StreamUsagePayload: {
            /** Format: int64 */
            tokens_in?: number;
            /** Format: int64 */
            tokens_out?: number;
            cost_usd?: number | null;
            model?: string;
        };
        StreamErrorPayload: {
            message: string;
            retriable?: boolean;
        };
        /**
         * @description Стартовое WS-сообщение — граница replay/live (T-04): всё до last_event_id
         *     уже отправлено догоном, дальше идёт live-поток.
         */
        SyncedMessage: {
            /** @enum {string} */
            type: "synced";
            /** Format: int64 */
            last_event_id: number;
        };
    };
    responses: {
        /** @description ошибка в едином формате */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ProjectId: number;
        PipelineId: number;
        RunId: string;
        GateId: string;
        StageId: number;
        /** @description ключ идемпотентности (D-12); не передан — сервер сгенерирует */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description демон жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description версия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description проекты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description проект с таким path уже существует (идемпотентность) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description проект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted?: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchProjectRequest"];
            };
        };
        responses: {
            /** @description обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjectPipelines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description пайплайны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description пайплайн */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePipelineRequest"];
            };
        };
        responses: {
            /** @description создан (версия 1) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPipelineRequest"];
            };
        };
        responses: {
            /** @description импортирован (новый пайплайн или новая версия) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPipelineVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description версии (desc) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPipelineVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePipelineVersionRequest"];
            };
        };
        responses: {
            /** @description создана версия N+1 с parent_version_id=id */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPipelineVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description версия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportPipelineVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description YAML пайплайна (стабильный порядок ключей) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/yaml": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                project_id?: number;
                pipeline_id?: number;
                state?: components["schemas"]["RunState"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description раны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description ключ идемпотентности (D-12); не передан — сервер сгенерирует */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description повтор Idempotency-Key — возвращён первый ран */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ран */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stopRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description ключ идемпотентности (D-12); не передан — сервер сгенерирует */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description остановлен (или уже остановлен) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description ключ идемпотентности (D-12); не передан — сервер сгенерирует */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ран возобновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: {
                /** @description ключ идемпотентности (D-12); не передан — сервер сгенерирует */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description заметка поставлена в очередь */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                after_id?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description страница событий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getArtifactContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
                artifactId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description содержимое файла (UTF-8) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description файл больше cap'а (5 МБ) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description метрики */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMetrics"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunMetricsCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV по попыткам этапов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProjectMetrics: {
        parameters: {
            query?: {
                period?: "24h" | "7d" | "30d" | "all";
            };
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description метрики проекта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMetrics"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resolveGate: {
        parameters: {
            query?: never;
            header?: {
                /** @description ключ идемпотентности (D-12); не передан — сервер сгенерирует */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["GateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveGateRequest"];
            };
        };
        responses: {
            /** @description гейт резолвнут */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveGateResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    interruptStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterruptStageRequest"];
            };
        };
        responses: {
            /** @description этап прерван, steer-заметка поставлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    pairTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairTelegramRequest"];
            };
        };
        responses: {
            /** @description чат привязан */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairTelegramResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description настройки (секреты замаскированы) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    putTelegramSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramSettingsPut"];
            };
        };
        responses: {
            /** @description сохранено и применено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putSupervisorSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupervisorSettingsPut"];
            };
        };
        responses: {
            /** @description сохранено и применено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupervisorSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    fsBrowse: {
        parameters: {
            query?: {
                /** @description абсолютный путь; пусто = домашний каталог */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description подкаталоги */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsBrowseResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLessons: {
        parameters: {
            query?: {
                status?: "proposed" | "confirmed" | "rejected" | "superseded";
                scope?: "global" | "project";
                project_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description уроки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description урок */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "proposed" | "confirmed" | "rejected" | "superseded";
                };
            };
        };
        responses: {
            /** @description обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    memoryTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description дерево памяти */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryTree"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    memoryReadFile: {
        parameters: {
            query: {
                scope: "global" | "project";
                vendor: string;
                project_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description содержимое */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFileContent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    memoryWriteFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWriteFileRequest"];
            };
        };
        responses: {
            /** @description сохранено (+ git commit для глобальной) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFileContent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    memoryHistory: {
        parameters: {
            query: {
                vendor: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description история */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryHistoryEntry"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    memoryPromote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryPromoteRequest"];
            };
        };
        responses: {
            /** @description продвинуто */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        path?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    eventsWs: {
        parameters: {
            query?: {
                /** @description ран для подписки; "*" — все раны (инбокс гейтов) */
                run_id?: string;
                last_event_id?: number;
                /** @description токен localhost-API (D-08), если настроен */
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket upgrade; далее Event | SyncedMessage */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description неверный/отсутствующий token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
