//go:build go1.22

// Package genapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package genapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for EventKind.
const (
	GateOpened        EventKind = "gate.opened"
	GateResolved      EventKind = "gate.resolved"
	RunBranchMismatch EventKind = "run.branch_mismatch"
	RunStateChanged   EventKind = "run.state_changed"
	StageInterrupted  EventKind = "stage.interrupted"
	StageQueued       EventKind = "stage.queued"
	StageResumed      EventKind = "stage.resumed"
	StageStateChanged EventKind = "stage.state_changed"
	StreamError       EventKind = "stream.error"
	StreamRaw         EventKind = "stream.raw"
	StreamText        EventKind = "stream.text"
	StreamThinking    EventKind = "stream.thinking"
	StreamToolCall    EventKind = "stream.tool_call"
	StreamToolResult  EventKind = "stream.tool_result"
	StreamUsage       EventKind = "stream.usage"
	System            EventKind = "system"
)

// Valid indicates whether the value is a known member of the EventKind enum.
func (e EventKind) Valid() bool {
	switch e {
	case GateOpened:
		return true
	case GateResolved:
		return true
	case RunBranchMismatch:
		return true
	case RunStateChanged:
		return true
	case StageInterrupted:
		return true
	case StageQueued:
		return true
	case StageResumed:
		return true
	case StageStateChanged:
		return true
	case StreamError:
		return true
	case StreamRaw:
		return true
	case StreamText:
		return true
	case StreamThinking:
		return true
	case StreamToolCall:
		return true
	case StreamToolResult:
		return true
	case StreamUsage:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for GateKind.
const (
	Escalation   GateKind = "escalation"
	FinalReview  GateKind = "final_review"
	PlanApproval GateKind = "plan_approval"
	Question     GateKind = "question"
)

// Valid indicates whether the value is a known member of the GateKind enum.
func (e GateKind) Valid() bool {
	switch e {
	case Escalation:
		return true
	case FinalReview:
		return true
	case PlanApproval:
		return true
	case Question:
		return true
	default:
		return false
	}
}

// Defines values for GateState.
const (
	Answered GateState = "answered"
	Approved GateState = "approved"
	Expired  GateState = "expired"
	Open     GateState = "open"
	Rejected GateState = "rejected"
)

// Valid indicates whether the value is a known member of the GateState enum.
func (e GateState) Valid() bool {
	switch e {
	case Answered:
		return true
	case Approved:
		return true
	case Expired:
		return true
	case Open:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for NoteKind.
const (
	NoteKindNote  NoteKind = "note"
	NoteKindSteer NoteKind = "steer"
)

// Valid indicates whether the value is a known member of the NoteKind enum.
func (e NoteKind) Valid() bool {
	switch e {
	case NoteKindNote:
		return true
	case NoteKindSteer:
		return true
	default:
		return false
	}
}

// Defines values for ResolveGateRequestAction.
const (
	Answer  ResolveGateRequestAction = "answer"
	Approve ResolveGateRequestAction = "approve"
	Comment ResolveGateRequestAction = "comment"
	Reject  ResolveGateRequestAction = "reject"
)

// Valid indicates whether the value is a known member of the ResolveGateRequestAction enum.
func (e ResolveGateRequestAction) Valid() bool {
	switch e {
	case Answer:
		return true
	case Approve:
		return true
	case Comment:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for RunState.
const (
	RunStateDraft       RunState = "draft"
	RunStateFailed      RunState = "failed"
	RunStateRunning     RunState = "running"
	RunStateStopped     RunState = "stopped"
	RunStateSucceeded   RunState = "succeeded"
	RunStateWaitingGate RunState = "waiting_gate"
)

// Valid indicates whether the value is a known member of the RunState enum.
func (e RunState) Valid() bool {
	switch e {
	case RunStateDraft:
		return true
	case RunStateFailed:
		return true
	case RunStateRunning:
		return true
	case RunStateStopped:
		return true
	case RunStateSucceeded:
		return true
	case RunStateWaitingGate:
		return true
	default:
		return false
	}
}

// Defines values for StageState.
const (
	StageStateFailed      StageState = "failed"
	StageStateInterrupted StageState = "interrupted"
	StageStatePending     StageState = "pending"
	StageStateRunning     StageState = "running"
	StageStateSkipped     StageState = "skipped"
	StageStateSucceeded   StageState = "succeeded"
)

// Valid indicates whether the value is a known member of the StageState enum.
func (e StageState) Valid() bool {
	switch e {
	case StageStateFailed:
		return true
	case StageStateInterrupted:
		return true
	case StageStatePending:
		return true
	case StageStateRunning:
		return true
	case StageStateSkipped:
		return true
	case StageStateSucceeded:
		return true
	default:
		return false
	}
}

// Artifact defines model for Artifact.
type Artifact struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Kind      string    `json:"kind"`
	Path      string    `json:"path"`
	RunId     string    `json:"run_id"`
	StageId   *int64    `json:"stage_id,omitempty"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Text string `json:"text"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	DefaultBranch *string `json:"default_branch,omitempty"`
	IdeCommand    *string `json:"ide_command,omitempty"`
	Name          string  `json:"name"`
	Path          string  `json:"path"`
}

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	// BaseBranch не указана — default_branch проекта
	BaseBranch *string `json:"base_branch,omitempty"`

	// Branch не указана — glamor/<slug> от base (D-31)
	Branch *string `json:"branch,omitempty"`
	Depth  *int64  `json:"depth,omitempty"`

	// Force override грязного чекаuta в preflight (D-34, T-10)
	Force             *bool  `json:"force,omitempty"`
	NotifyTg          *bool  `json:"notify_tg,omitempty"`
	PipelineVersionId int64  `json:"pipeline_version_id"`
	ProjectId         int64  `json:"project_id"`
	TaskText          string `json:"task_text"`
}

// Error defines model for Error.
type Error struct {
	// Code доменный код: not_found, invalid_transition, run_locked,
	// gate_already_resolved, duplicate, draining, validation, internal
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Event Событие журнала (D-11). Приходит по WS (/ws) и возвращается Replay-API.
// kind-пространства: run.*, stage.*, gate.*, stream.*, notify.*.
type Event struct {
	// Id монотонный id журнала (AUTOINCREMENT)
	Id   int64     `json:"id"`
	Kind EventKind `json:"kind"`

	// Payload Полиморфный payload события (детерминирован kind'ом события):
	// - run.state_changed / stage.state_changed → StateChangedPayload
	// - gate.opened / gate.resolved → GatePayload
	// - stream.thinking / stream.text / stream.raw → StreamTextPayload
	// - stream.tool_call / stream.tool_result → StreamToolPayload
	// - stream.usage → StreamUsagePayload
	// - stream.error → StreamErrorPayload
	Payload EventPayload `json:"payload"`

	// RunId uuid рана; "*" зарезервировано для подписки «все раны»
	RunId   string    `json:"run_id"`
	StageId *int64    `json:"stage_id,omitempty"`
	Ts      time.Time `json:"ts"`
}

// EventKind defines model for EventKind.
type EventKind string

// EventPayload Полиморфный payload события (детерминирован kind'ом события):
// - run.state_changed / stage.state_changed → StateChangedPayload
// - gate.opened / gate.resolved → GatePayload
// - stream.thinking / stream.text / stream.raw → StreamTextPayload
// - stream.tool_call / stream.tool_result → StreamToolPayload
// - stream.usage → StreamUsagePayload
// - stream.error → StreamErrorPayload
type EventPayload map[string]interface{}

// Gate defines model for Gate.
type Gate struct {
	Answer      *string    `json:"answer,omitempty"`
	ContextJson *string    `json:"context_json,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Id          string     `json:"id"`
	Kind        GateKind   `json:"kind"`
	Question    string     `json:"question"`
	ResolvedAt  *time.Time `json:"resolved_at,omitempty"`
	RunId       string     `json:"run_id"`
	StageId     *int64     `json:"stage_id,omitempty"`
	State       GateState  `json:"state"`
}

// GateKind defines model for GateKind.
type GateKind string

// GateState defines model for GateState.
type GateState string

// InterruptStageRequest defines model for InterruptStageRequest.
type InterruptStageRequest struct {
	// Message steer-сообщение — сессия резюмится с ним (D-22)
	Message string `json:"message"`
}

// Note defines model for Note.
type Note struct {
	Consumed  bool      `json:"consumed"`
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Kind      *NoteKind `json:"kind,omitempty"`
	RunId     string    `json:"run_id"`
	StageId   *int64    `json:"stage_id,omitempty"`
	Text      string    `json:"text"`
}

// NoteKind defines model for Note.Kind.
type NoteKind string

// PatchProjectRequest defines model for PatchProjectRequest.
type PatchProjectRequest struct {
	DefaultBranch *string `json:"default_branch,omitempty"`
	IdeCommand    *string `json:"ide_command,omitempty"`
}

// Pipeline defines model for Pipeline.
type Pipeline struct {
	CreatedAt       time.Time `json:"created_at"`
	Id              int64     `json:"id"`
	Name            string    `json:"name"`
	ParentVersionId *int64    `json:"parent_version_id,omitempty"`

	// ProjectId NULL = глобальный пайплайн
	ProjectId *int64 `json:"project_id"`
	SpecJson  string `json:"spec_json"`
	Version   int64  `json:"version"`
}

// PipelineDetail defines model for PipelineDetail.
type PipelineDetail struct {
	CreatedAt       time.Time `json:"created_at"`
	Id              int64     `json:"id"`
	Name            string    `json:"name"`
	ParentVersionId *int64    `json:"parent_version_id,omitempty"`

	// ProjectId NULL = глобальный пайплайн
	ProjectId *int64     `json:"project_id"`
	SpecJson  string     `json:"spec_json"`
	Version   int64      `json:"version"`
	Versions  []Pipeline `json:"versions"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt     time.Time `json:"created_at"`
	DefaultBranch string    `json:"default_branch"`
	Id            int64     `json:"id"`
	IdeCommand    string    `json:"ide_command"`
	Name          string    `json:"name"`
	Path          string    `json:"path"`
}

// ProjectDetail defines model for ProjectDetail.
type ProjectDetail struct {
	ActiveRuns    []Run     `json:"active_runs"`
	CreatedAt     time.Time `json:"created_at"`
	DefaultBranch string    `json:"default_branch"`
	Id            int64     `json:"id"`
	IdeCommand    string    `json:"ide_command"`
	Name          string    `json:"name"`

	// OpenGates открытые гейты по всем активным ранам проекта
	OpenGates int    `json:"open_gates"`
	Path      string `json:"path"`
}

// ResolveGateRequest defines model for ResolveGateRequest.
type ResolveGateRequest struct {
	Action ResolveGateRequestAction `json:"action"`
	Text   *string                  `json:"text,omitempty"`
}

// ResolveGateRequestAction defines model for ResolveGateRequest.Action.
type ResolveGateRequestAction string

// ResolveGateResponse defines model for ResolveGateResponse.
type ResolveGateResponse struct {
	AlreadyResolved bool `json:"already_resolved"`
	Gate            Gate `json:"gate"`
}

// Run defines model for Run.
type Run struct {
	BaseBranch        string     `json:"base_branch"`
	Branch            string     `json:"branch"`
	CreatedAt         time.Time  `json:"created_at"`
	Depth             int64      `json:"depth"`
	FinishedAt        *time.Time `json:"finished_at,omitempty"`
	Id                string     `json:"id"`
	NotifyTg          bool       `json:"notify_tg"`
	PipelineVersionId int64      `json:"pipeline_version_id"`
	ProjectId         int64      `json:"project_id"`
	State             RunState   `json:"state"`
	TaskText          string     `json:"task_text"`
}

// RunDetail defines model for RunDetail.
type RunDetail struct {
	Artifacts         []Artifact `json:"artifacts"`
	BaseBranch        string     `json:"base_branch"`
	Branch            string     `json:"branch"`
	CreatedAt         time.Time  `json:"created_at"`
	Depth             int64      `json:"depth"`
	FinishedAt        *time.Time `json:"finished_at,omitempty"`
	Gates             []Gate     `json:"gates"`
	Id                string     `json:"id"`
	Notes             []Note     `json:"notes"`
	NotifyTg          bool       `json:"notify_tg"`
	PipelineVersionId int64      `json:"pipeline_version_id"`
	ProjectId         int64      `json:"project_id"`
	Stages            []Stage    `json:"stages"`
	State             RunState   `json:"state"`
	TaskText          string     `json:"task_text"`
}

// RunState defines model for RunState.
type RunState string

// Stage defines model for Stage.
type Stage struct {
	Error           *string    `json:"error,omitempty"`
	ExitCode        *int64     `json:"exit_code,omitempty"`
	FinishedAt      *time.Time `json:"finished_at,omitempty"`
	Harness         string     `json:"harness"`
	Id              int64      `json:"id"`
	Iteration       int64      `json:"iteration"`
	Pid             *int64     `json:"pid,omitempty"`
	ResumeCount     int64      `json:"resume_count"`
	RunId           string     `json:"run_id"`
	SessionId       *string    `json:"session_id,omitempty"`
	StageKey        string     `json:"stage_key"`
	StartedAt       *time.Time `json:"started_at,omitempty"`
	State           StageState `json:"state"`
	StopRequestedBy *string    `json:"stop_requested_by,omitempty"`
	TokensIn        int64      `json:"tokens_in"`
	TokensOut       int64      `json:"tokens_out"`
}

// StageState defines model for StageState.
type StageState string

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	// Harnesses доступные harness-адаптеры (exec.LookPath при старте, T-06)
	Harnesses *[]string `json:"harnesses,omitempty"`
	Version   string    `json:"version"`
}

// GateId defines model for GateId.
type GateId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// PipelineId defines model for PipelineId.
type PipelineId = int64

// ProjectId defines model for ProjectId.
type ProjectId = int64

// RunId defines model for RunId.
type RunId = string

// StageId defines model for StageId.
type StageId = int64

// ResolveGateParams defines parameters for ResolveGate.
type ResolveGateParams struct {
	// IdempotencyKey ключ идемпотентности (D-12); не передан — сервер сгенерирует
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	ProjectId  *int64    `form:"project_id,omitempty" json:"project_id,omitempty"`
	PipelineId *int64    `form:"pipeline_id,omitempty" json:"pipeline_id,omitempty"`
	State      *RunState `form:"state,omitempty" json:"state,omitempty"`
	Limit      *int      `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateRunParams defines parameters for CreateRun.
type CreateRunParams struct {
	// IdempotencyKey ключ идемпотентности (D-12); не передан — сервер сгенерирует
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListRunEventsParams defines parameters for ListRunEvents.
type ListRunEventsParams struct {
	AfterId *int64 `form:"after_id,omitempty" json:"after_id,omitempty"`
	Limit   *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateNoteParams defines parameters for CreateNote.
type CreateNoteParams struct {
	// IdempotencyKey ключ идемпотентности (D-12); не передан — сервер сгенерирует
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ResumeRunParams defines parameters for ResumeRun.
type ResumeRunParams struct {
	// IdempotencyKey ключ идемпотентности (D-12); не передан — сервер сгенерирует
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// StopRunParams defines parameters for StopRun.
type StopRunParams struct {
	// IdempotencyKey ключ идемпотентности (D-12); не передан — сервер сгенерирует
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// EventsWsParams defines parameters for EventsWs.
type EventsWsParams struct {
	// RunId ран для подписки; "*" — все раны (инбокс гейтов)
	RunId       *string `form:"run_id,omitempty" json:"run_id,omitempty"`
	LastEventId *int64  `form:"last_event_id,omitempty" json:"last_event_id,omitempty"`

	// Token токен localhost-API (D-08), если настроен
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// ResolveGateJSONRequestBody defines body for ResolveGate for application/json ContentType.
type ResolveGateJSONRequestBody = ResolveGateRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// PatchProjectJSONRequestBody defines body for PatchProject for application/json ContentType.
type PatchProjectJSONRequestBody = PatchProjectRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// InterruptStageJSONRequestBody defines body for InterruptStage for application/json ContentType.
type InterruptStageJSONRequestBody = InterruptStageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ResolveGate Резолв гейта (идемпотентно; повтор → 200 + already_resolved)
	// (POST /gates/{id}/resolve)
	ResolveGate(w http.ResponseWriter, r *http.Request, id GateId, params ResolveGateParams)
	// Healthz Liveness probe демона (без auth)
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// GetPipeline Версия пайплайна со списком всех версий
	// (GET /pipelines/{id})
	GetPipeline(w http.ResponseWriter, r *http.Request, id PipelineId)
	// ListProjects Список проектов
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// CreateProject Зарегистрировать проект
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// GetProject Проект с активными ранами и счётчиком открытых гейтов
	// (GET /projects/{id})
	GetProject(w http.ResponseWriter, r *http.Request, id ProjectId)
	// PatchProject Обновить ide_command / default_branch
	// (PATCH /projects/{id})
	PatchProject(w http.ResponseWriter, r *http.Request, id ProjectId)
	// ListProjectPipelines Пайплайны проекта (+ глобальные)
	// (GET /projects/{id}/pipelines)
	ListProjectPipelines(w http.ResponseWriter, r *http.Request, id ProjectId)
	// ListRuns Список ранов с фильтрами
	// (GET /runs)
	ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams)
	// CreateRun Создать ран (идемпотентно, D-12)
	// (POST /runs)
	CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams)
	// GetRun Полный срез рана (стадии, гейты, артефакты)
	// (GET /runs/{id})
	GetRun(w http.ResponseWriter, r *http.Request, id RunId)
	// ListRunEvents REST-доступ к журналу событий рана
	// (GET /runs/{id}/events)
	ListRunEvents(w http.ResponseWriter, r *http.Request, id RunId, params ListRunEventsParams)
	// CreateNote Queue note к ближайшему событию рана (D-22)
	// (POST /runs/{id}/notes)
	CreateNote(w http.ResponseWriter, r *http.Request, id RunId, params CreateNoteParams)
	// ResumeRun Ручной рестарт failed/interrupted рана
	// (POST /runs/{id}/resume)
	ResumeRun(w http.ResponseWriter, r *http.Request, id RunId, params ResumeRunParams)
	// StopRun Остановить ран (идемпотентно, D-14)
	// (POST /runs/{id}/stop)
	StopRun(w http.ResponseWriter, r *http.Request, id RunId, params StopRunParams)
	// InterruptStage Interrupt & Steer (D-22) — прервать этап и резюмить с сообщением
	// (POST /stages/{id}/interrupt)
	InterruptStage(w http.ResponseWriter, r *http.Request, id StageId)
	// Version Версия демона
	// (GET /version)
	Version(w http.ResponseWriter, r *http.Request)
	// EventsWs WebSocket-поток событий журнала (D-04)
	// (GET /ws)
	EventsWs(w http.ResponseWriter, r *http.Request, params EventsWsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ResolveGate operation middleware
func (siw *ServerInterfaceWrapper) ResolveGate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id GateId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResolveGateParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveGate(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPipeline operation middleware
func (siw *ServerInterfaceWrapper) GetPipeline(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PipelineId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPipeline(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchProject operation middleware
func (siw *ServerInterfaceWrapper) PatchProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectPipelines operation middleware
func (siw *ServerInterfaceWrapper) ListProjectPipelines(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectPipelines(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRuns operation middleware
func (siw *ServerInterfaceWrapper) ListRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project_id", r.URL.Query(), &params.ProjectId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pipeline_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pipeline_id", r.URL.Query(), &params.PipelineId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pipeline_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pipeline_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRunParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunEventsParams

	// ------------- Optional query parameter "after_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after_id", r.URL.Query(), &params.AfterId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunEvents(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateNoteParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeRun operation middleware
func (siw *ServerInterfaceWrapper) ResumeRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResumeRunParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeRun(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopRun operation middleware
func (siw *ServerInterfaceWrapper) StopRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RunId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StopRunParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopRun(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InterruptStage operation middleware
func (siw *ServerInterfaceWrapper) InterruptStage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StageId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InterruptStage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Version operation middleware
func (siw *ServerInterfaceWrapper) Version(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Version(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EventsWs operation middleware
func (siw *ServerInterfaceWrapper) EventsWs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params EventsWsParams

	// ------------- Optional query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "run_id", r.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "run_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "last_event_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last_event_id", r.URL.Query(), &params.LastEventId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "last_event_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last_event_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EventsWs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.Version)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{id}", wrapper.GetProject)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/projects/{id}", wrapper.PatchProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{id}/pipelines", wrapper.ListProjectPipelines)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pipelines/{id}", wrapper.GetPipeline)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs", wrapper.ListRuns)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs", wrapper.CreateRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}", wrapper.GetRun)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs/{id}/stop", wrapper.StopRun)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs/{id}/resume", wrapper.ResumeRun)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs/{id}/notes", wrapper.CreateNote)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{id}/events", wrapper.ListRunEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/gates/{id}/resolve", wrapper.ResolveGate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/stages/{id}/interrupt", wrapper.InterruptStage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ws", wrapper.EventsWs)

	return m
}

type ErrorJSONResponse Error

type ResolveGateRequestObject struct {
	Id     GateId `json:"id"`
	Params ResolveGateParams
	Body   *ResolveGateJSONRequestBody
}

type ResolveGateResponseObject interface {
	VisitResolveGateResponse(w http.ResponseWriter) error
}

type ResolveGate200JSONResponse ResolveGateResponse

func (response ResolveGate200JSONResponse) VisitResolveGateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveGatedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ResolveGatedefaultJSONResponse) VisitResolveGateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200TextResponse string

func (response Healthz200TextResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetPipelineRequestObject struct {
	Id PipelineId `json:"id"`
}

type GetPipelineResponseObject interface {
	VisitGetPipelineResponse(w http.ResponseWriter) error
}

type GetPipeline200JSONResponse PipelineDetail

func (response GetPipeline200JSONResponse) VisitGetPipelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPipelinedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetPipelinedefaultJSONResponse) VisitGetPipelineResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsRequestObject struct {
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse []Project

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListProjectsdefaultJSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectRequestObject struct {
	Body *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject200JSONResponse Project

func (response CreateProject200JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateProjectdefaultJSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectRequestObject struct {
	Id ProjectId `json:"id"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse ProjectDetail

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProjectdefaultJSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PatchProjectRequestObject struct {
	Id   ProjectId `json:"id"`
	Body *PatchProjectJSONRequestBody
}

type PatchProjectResponseObject interface {
	VisitPatchProjectResponse(w http.ResponseWriter) error
}

type PatchProject200JSONResponse Project

func (response PatchProject200JSONResponse) VisitPatchProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PatchProjectdefaultJSONResponse) VisitPatchProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectPipelinesRequestObject struct {
	Id ProjectId `json:"id"`
}

type ListProjectPipelinesResponseObject interface {
	VisitListProjectPipelinesResponse(w http.ResponseWriter) error
}

type ListProjectPipelines200JSONResponse []Pipeline

func (response ListProjectPipelines200JSONResponse) VisitListProjectPipelinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectPipelinesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListProjectPipelinesdefaultJSONResponse) VisitListProjectPipelinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunsRequestObject struct {
	Params ListRunsParams
}

type ListRunsResponseObject interface {
	VisitListRunsResponse(w http.ResponseWriter) error
}

type ListRuns200JSONResponse []Run

func (response ListRuns200JSONResponse) VisitListRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListRunsdefaultJSONResponse) VisitListRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRunRequestObject struct {
	Params CreateRunParams
	Body   *CreateRunJSONRequestBody
}

type CreateRunResponseObject interface {
	VisitCreateRunResponse(w http.ResponseWriter) error
}

type CreateRun200JSONResponse Run

func (response CreateRun200JSONResponse) VisitCreateRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRun201JSONResponse Run

func (response CreateRun201JSONResponse) VisitCreateRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRundefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateRundefaultJSONResponse) VisitCreateRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRunRequestObject struct {
	Id RunId `json:"id"`
}

type GetRunResponseObject interface {
	VisitGetRunResponse(w http.ResponseWriter) error
}

type GetRun200JSONResponse RunDetail

func (response GetRun200JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRundefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetRundefaultJSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunEventsRequestObject struct {
	Id     RunId `json:"id"`
	Params ListRunEventsParams
}

type ListRunEventsResponseObject interface {
	VisitListRunEventsResponse(w http.ResponseWriter) error
}

type ListRunEvents200JSONResponse []Event

func (response ListRunEvents200JSONResponse) VisitListRunEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunEventsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListRunEventsdefaultJSONResponse) VisitListRunEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNoteRequestObject struct {
	Id     RunId `json:"id"`
	Params CreateNoteParams
	Body   *CreateNoteJSONRequestBody
}

type CreateNoteResponseObject interface {
	VisitCreateNoteResponse(w http.ResponseWriter) error
}

type CreateNote201JSONResponse Note

func (response CreateNote201JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateNotedefaultJSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeRunRequestObject struct {
	Id     RunId `json:"id"`
	Params ResumeRunParams
}

type ResumeRunResponseObject interface {
	VisitResumeRunResponse(w http.ResponseWriter) error
}

type ResumeRun200JSONResponse Run

func (response ResumeRun200JSONResponse) VisitResumeRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResumeRundefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ResumeRundefaultJSONResponse) VisitResumeRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StopRunRequestObject struct {
	Id     RunId `json:"id"`
	Params StopRunParams
}

type StopRunResponseObject interface {
	VisitStopRunResponse(w http.ResponseWriter) error
}

type StopRun200JSONResponse Run

func (response StopRun200JSONResponse) VisitStopRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopRundefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StopRundefaultJSONResponse) VisitStopRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type InterruptStageRequestObject struct {
	Id   StageId `json:"id"`
	Body *InterruptStageJSONRequestBody
}

type InterruptStageResponseObject interface {
	VisitInterruptStageResponse(w http.ResponseWriter) error
}

type InterruptStage200JSONResponse Stage

func (response InterruptStage200JSONResponse) VisitInterruptStageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type InterruptStagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response InterruptStagedefaultJSONResponse) VisitInterruptStageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type VersionRequestObject struct {
}

type VersionResponseObject interface {
	VisitVersionResponse(w http.ResponseWriter) error
}

type Version200JSONResponse VersionInfo

func (response Version200JSONResponse) VisitVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EventsWsRequestObject struct {
	Params EventsWsParams
}

type EventsWsResponseObject interface {
	VisitEventsWsResponse(w http.ResponseWriter) error
}

type EventsWs101Response struct {
}

func (response EventsWs101Response) VisitEventsWsResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type EventsWs401Response struct {
}

func (response EventsWs401Response) VisitEventsWsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ResolveGate Резолв гейта (идемпотентно; повтор → 200 + already_resolved)
	// (POST /gates/{id}/resolve)
	ResolveGate(ctx context.Context, request ResolveGateRequestObject) (ResolveGateResponseObject, error)
	// Healthz Liveness probe демона (без auth)
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// GetPipeline Версия пайплайна со списком всех версий
	// (GET /pipelines/{id})
	GetPipeline(ctx context.Context, request GetPipelineRequestObject) (GetPipelineResponseObject, error)
	// ListProjects Список проектов
	// (GET /projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// CreateProject Зарегистрировать проект
	// (POST /projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// GetProject Проект с активными ранами и счётчиком открытых гейтов
	// (GET /projects/{id})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// PatchProject Обновить ide_command / default_branch
	// (PATCH /projects/{id})
	PatchProject(ctx context.Context, request PatchProjectRequestObject) (PatchProjectResponseObject, error)
	// ListProjectPipelines Пайплайны проекта (+ глобальные)
	// (GET /projects/{id}/pipelines)
	ListProjectPipelines(ctx context.Context, request ListProjectPipelinesRequestObject) (ListProjectPipelinesResponseObject, error)
	// ListRuns Список ранов с фильтрами
	// (GET /runs)
	ListRuns(ctx context.Context, request ListRunsRequestObject) (ListRunsResponseObject, error)
	// CreateRun Создать ран (идемпотентно, D-12)
	// (POST /runs)
	CreateRun(ctx context.Context, request CreateRunRequestObject) (CreateRunResponseObject, error)
	// GetRun Полный срез рана (стадии, гейты, артефакты)
	// (GET /runs/{id})
	GetRun(ctx context.Context, request GetRunRequestObject) (GetRunResponseObject, error)
	// ListRunEvents REST-доступ к журналу событий рана
	// (GET /runs/{id}/events)
	ListRunEvents(ctx context.Context, request ListRunEventsRequestObject) (ListRunEventsResponseObject, error)
	// CreateNote Queue note к ближайшему событию рана (D-22)
	// (POST /runs/{id}/notes)
	CreateNote(ctx context.Context, request CreateNoteRequestObject) (CreateNoteResponseObject, error)
	// ResumeRun Ручной рестарт failed/interrupted рана
	// (POST /runs/{id}/resume)
	ResumeRun(ctx context.Context, request ResumeRunRequestObject) (ResumeRunResponseObject, error)
	// StopRun Остановить ран (идемпотентно, D-14)
	// (POST /runs/{id}/stop)
	StopRun(ctx context.Context, request StopRunRequestObject) (StopRunResponseObject, error)
	// InterruptStage Interrupt & Steer (D-22) — прервать этап и резюмить с сообщением
	// (POST /stages/{id}/interrupt)
	InterruptStage(ctx context.Context, request InterruptStageRequestObject) (InterruptStageResponseObject, error)
	// Version Версия демона
	// (GET /version)
	Version(ctx context.Context, request VersionRequestObject) (VersionResponseObject, error)
	// EventsWs WebSocket-поток событий журнала (D-04)
	// (GET /ws)
	EventsWs(ctx context.Context, request EventsWsRequestObject) (EventsWsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ResolveGate operation middleware
func (sh *strictHandler) ResolveGate(w http.ResponseWriter, r *http.Request, id GateId, params ResolveGateParams) {
	var request ResolveGateRequestObject

	request.Id = id
	request.Params = params

	var body ResolveGateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveGate(ctx, request.(ResolveGateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveGate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveGateResponseObject); ok {
		if err := validResponse.VisitResolveGateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPipeline operation middleware
func (sh *strictHandler) GetPipeline(w http.ResponseWriter, r *http.Request, id PipelineId) {
	var request GetPipelineRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPipeline(ctx, request.(GetPipelineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPipeline")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPipelineResponseObject); ok {
		if err := validResponse.VisitGetPipelineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(w http.ResponseWriter, r *http.Request) {
	var request ListProjectsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx, request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		if err := validResponse.VisitListProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(w http.ResponseWriter, r *http.Request) {
	var request CreateProjectRequestObject

	var body CreateProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(w http.ResponseWriter, r *http.Request, id ProjectId) {
	var request GetProjectRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchProject operation middleware
func (sh *strictHandler) PatchProject(w http.ResponseWriter, r *http.Request, id ProjectId) {
	var request PatchProjectRequestObject

	request.Id = id

	var body PatchProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchProject(ctx, request.(PatchProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchProjectResponseObject); ok {
		if err := validResponse.VisitPatchProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjectPipelines operation middleware
func (sh *strictHandler) ListProjectPipelines(w http.ResponseWriter, r *http.Request, id ProjectId) {
	var request ListProjectPipelinesRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjectPipelines(ctx, request.(ListProjectPipelinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjectPipelines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectPipelinesResponseObject); ok {
		if err := validResponse.VisitListProjectPipelinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRuns operation middleware
func (sh *strictHandler) ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams) {
	var request ListRunsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRuns(ctx, request.(ListRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRuns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRunsResponseObject); ok {
		if err := validResponse.VisitListRunsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRun operation middleware
func (sh *strictHandler) CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams) {
	var request CreateRunRequestObject

	request.Params = params

	var body CreateRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRun(ctx, request.(CreateRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRunResponseObject); ok {
		if err := validResponse.VisitCreateRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRun operation middleware
func (sh *strictHandler) GetRun(w http.ResponseWriter, r *http.Request, id RunId) {
	var request GetRunRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRun(ctx, request.(GetRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRunResponseObject); ok {
		if err := validResponse.VisitGetRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRunEvents operation middleware
func (sh *strictHandler) ListRunEvents(w http.ResponseWriter, r *http.Request, id RunId, params ListRunEventsParams) {
	var request ListRunEventsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRunEvents(ctx, request.(ListRunEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRunEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRunEventsResponseObject); ok {
		if err := validResponse.VisitListRunEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNote operation middleware
func (sh *strictHandler) CreateNote(w http.ResponseWriter, r *http.Request, id RunId, params CreateNoteParams) {
	var request CreateNoteRequestObject

	request.Id = id
	request.Params = params

	var body CreateNoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNote(ctx, request.(CreateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNoteResponseObject); ok {
		if err := validResponse.VisitCreateNoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeRun operation middleware
func (sh *strictHandler) ResumeRun(w http.ResponseWriter, r *http.Request, id RunId, params ResumeRunParams) {
	var request ResumeRunRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeRun(ctx, request.(ResumeRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeRunResponseObject); ok {
		if err := validResponse.VisitResumeRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopRun operation middleware
func (sh *strictHandler) StopRun(w http.ResponseWriter, r *http.Request, id RunId, params StopRunParams) {
	var request StopRunRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopRun(ctx, request.(StopRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopRunResponseObject); ok {
		if err := validResponse.VisitStopRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InterruptStage operation middleware
func (sh *strictHandler) InterruptStage(w http.ResponseWriter, r *http.Request, id StageId) {
	var request InterruptStageRequestObject

	request.Id = id

	var body InterruptStageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InterruptStage(ctx, request.(InterruptStageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InterruptStage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InterruptStageResponseObject); ok {
		if err := validResponse.VisitInterruptStageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Version operation middleware
func (sh *strictHandler) Version(w http.ResponseWriter, r *http.Request) {
	var request VersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Version(ctx, request.(VersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Version")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VersionResponseObject); ok {
		if err := validResponse.VisitVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EventsWs operation middleware
func (sh *strictHandler) EventsWs(w http.ResponseWriter, r *http.Request, params EventsWsParams) {
	var request EventsWsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EventsWs(ctx, request.(EventsWsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventsWs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EventsWsResponseObject); ok {
		if err := validResponse.VisitEventsWsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fxbb9xGlv4rBe4CIyXsi5RsdtDBPngSI2PE49FKzuRhZHTKzVKLIzbJkEXZWq8WumTiCZxNkGCBfVls",
	"Js/70paluK1LC5hfUPUX5pcszqkiu8gmu1vXDObFbraKdTnnO/dT/czqBL0w8JnPY6v1zAppRHuMswif",
	"PqKc3XPgk+tbLSukfN2yLZ/2mNWyXMeyrYh9nrgRc6wWjxJmW3FnnfUovMG3QhgV88j1u9b2tm3dc1gv",
	"DDjzO1sfsy0Y47C4E7khdwOYXhyLE/mNfE7EQByKI3EqzsVQ7okjcSb3xJkYyl25JwZk7sPawuL8+0Sc",
	"iSMizsWR3BFH4lD0xRn5685/EbmLXx3Av/DwCmbArwZyR+6LI7ln2epE64w6LBqdydhiDfY4+UBLbsg8",
	"1780idaCqEc5jPP5e+9adrqE63PWZZFaIwr+wDr8JpdYTvzrY/IKp90bJMg2vB6HgR8zROjdKAoi+NAJ",
	"fM58Dh9pGHpuhwKqGn+IAVrPjDX+MWJrVsv6h8YI+A3117ihZsNVCtAcyj+JgXgpjkWfiAOCeBsAJsUp",
	"kV+IodwRp6IPYEUq6AlhvTsRd9doB3cWRkHIIu6qvXciRjlz2pTnzu5Qzmrc7bHR+VP62kDAWehkWxuu",
	"75RwyFYMKftDlPhtt/ydGJjarljbTzyPPvZYys4ShI04/nsNAbWWncIDd2ubFHmUTRQ8BgGAbXyAf34Q",
	"cLbMPk9YXEJTzp7ycmCae8BR1StomatcxGFrNPF4+3FE/U45MV2HtTtBr0cruKDkYXb2FA5gSlX1OZYT",
	"v/IMj2nMjAMU4A6aVe4D2sVr0Kuij5o1f3AizuWOGIojcSz3RL8MrhddoOvRXhA1VpNm851O7CVd/MQI",
	"2AECWwbl/87CfNlaDgv5usEeq9W0Z5GUtSDqsNx7a9SLWVEFBJssilyHEfFK7shvxWuU/ldiSORzIIHo",
	"J5yCbggjtua53XWOe33XJg9rC01jx4+DwGPURxQE3F3bavNubvmcGBmjQ21u2pssit3Ab8+sDEIF6Nlf",
	"4DTeaM8mS8bc5Vs0ZyvDaqbCC9oxcFgJcA5B5aJBP5MvxBsijsVQHLaIH/D2WpD4jk1cf5N6rtPmEfVj",
	"F160CSgcL+hsMMde9buUszb1IkadrXbE4sDbZI5NnETZDWYTJ6Ku7/pdm+BUVE0CBIp86q365fjj1PVw",
	"79RxcF3qLRlnyvF1dP4ei2PaZdMpjRQZjS+l5aa2gQWq/SiG4qV8Ae4T+Ew/yX25A0InTkQf/amF+ToR",
	"P6CL9EcgqBjIPfCthuTTFTLXeBLPEzEg4kAMxWtxIHdEX34l+uBKyV35LVlmoUe3aneW7tVXfVDmNaUb",
	"wGODweIMfbcD0W8BK+pv2QRtCnwAbqgvIkZ78EmJRf2tOhI6DwsF4cLxTsUQ/cM9/F8Bw3XGznnnk4e/",
	"vffgg+W7v7n74CFI5AXs6ES3Aaj+MQxEBb7lBXS2d5b02Jz1zZ8tSVyHKBKK/vtk1Xpr1SKgM9Hpfa09",
	"3QEq4gMcNSTiUJzIb5F94lCci4HcFcdiQP7yf+IAnGM9n3zxl5MyIF/J2tuWCiRmcWcmegY8HvkFKU0r",
	"If+x5hLzkx5MBRiLOYh5Z536XaZnrit71O65cY/yDphQBcPiWPXt5wlLjEcU/ygJufFdxOKkh88I4yBk",
	"/ugpVS04GsHN110Qj67xDajF0VMQeO0O9bzCV7CMZ4xLUANkjwxVaPYY0SfwsBVz1jNoNuJwDnxT9FVB",
	"1H4QQ3EiBiByckd+oYVNMwiirUzRyG/JHMRx4BSjewz+sgFUAsz9hfKgc6/Nt1b9GhljIWmQEmaRv375",
	"PVmBbz5QX+hjwRQGS0iD5FiCr0F4awwv8AjXy3g0eoroE70oPD5kT3nJHCkfjUlGfDRfDwJv/HVkrzHq",
	"E3geH4ZsN4ahJc2GWSXCAiceN7XUj58wNMEV0j1CDoZZT3k7javGB1w6qBn7ehbVCwdKNS96um7FvlLG",
	"T9rY1NPfVIiEryvOTDssQn2K6tRaM6NHOv3UACujpqFKQ4/6bRqGUbBJvfysLO5Qj+qHNdenAPBNlz0p",
	"VTqj3Ruzg3RatkYgakq1lNLYDDaGH9nTEM9aNvG9VC9j7qEy4jH8rLxOizljUQ11EGihr9C7BD8pSybt",
	"yl3UZ8rmym9AmWnPR+4SHH0KbtTi4vxUKzfJfYPQtswT9pWRGeHOiApuJYuQsssPuDI7jEWlvLg5CZkt",
	"Gin4EMq4ZgScKgBL4BXcePi/XbayjpxuOU00IQ8RMZ9PCzWnsy0feuYF78En9++TfyHilTgByQM3XX6d",
	"xnXnoi/eiHPw3MUbcVbmrc+gVkPWqbZV+nCz5knHcJYLfZGSoznNtafDTjP/Qwwh0SR73m/XrNbvJxuE",
	"DDTbdhE1eh8qZuKsF08zLsZc6QZpFNGtsaNnM4+f5NEoYX09OJ5J1GaE+g2n5Mx0psZCYff5LUwHhSLk",
	"hTGh6T8OCdrh7iZrR8kFULGc+OOAsNFst8GhjkuicYjDj+UOuPPyhTgiWIB5Aw8qo6CCUHFKRB8zhwNx",
	"gEJ/msW58LeK3GKVQJqHy+2vHKXLyh0En6RSz8OUSjuk5k/7JplrknkuaGR6PebzUqs4m+3S65VhIbdd",
	"Vf4o2W8ho1XuL3RndDTHttdVLuTYKqX7TfypKecJyeJriSqyfPAsOWDXd+P1K0YHFX5PLsn7s2Z1Zwoy",
	"lhNfxxgXSgOPG8RpuWA7B4iM/aNgRTHQJOBUnbmc+BfVl0rDjcmSrtrNrimzOl+Jusw05UwzfZRSvzAL",
	"ON+zz4KxRMks6IbPPg3GVFN9Aj1pelLboF+67wo9nKLN0LJORNe4cuN9lSt7Ql3u+t22VkFx0ukw5qBD",
	"v0ZdT2fYgjCsiBDVIcYUEksrD1NFmz11eTutSFzCD70W/bJOI5/F8RW9IM4iymf1ekGKL+v5q9RouxMk",
	"Pp9xsUnRI4sN7TiVVirY3FBtJmV/jfgVuTGTMkXgZeoUINqOlLvBnPbjrZmOwoMN5sdtd1aO6fFBwi8d",
	"2GQB9IiMJnJGKjqFZIHb5qZzGyrT2QaNzLQT8x0l/CM1UCr3haz8hlupBX6n7NA9fy0Y1wX6JKUO7aEu",
	"ZO2Lc3RUj4geXRN97Ds6Vzlu+YLMsaesU78fBBtLlOsK+YBg8asvd2CYTR7Wmu/NK4L2yqW5qLONQHWy",
	"FU4HjtMZRrr65Pnj/frhwyVyZ+keEQPy6UqtkMLXnVhDLNGr8rxD5j6sNRdbRO6Kc1X6xlRZHCRRh5Fg",
	"jfAo4ev2qv9RQGCjHV6LWbTJIvI2wblgzhOgy3PdvPWaBDR0a6Bhu8y3ycOVGgYG5/KFMWjVB78eBsLh",
	"1BnSJN1pnch9uSeG8rk4yzJ4sE/VPLDYXHyv1vxlbeG9+fqqL77HOpg4xXf68ksxEIOKvjPgKnactYhq",
	"FyOfFdrEPquv+ncSvt4iv2I0YlENC5HHMAGS6pfzBMkHgY/8ziYQHakyNmmsM+rx9X97Py3aNZ7EeKTP",
	"ExZt1cQ5Fvr6MFbuyR1VEeUuB31hKXYQh7Je4AMLjfxDy2rWF+rNNFijoWu1rHfqzfo7OkxF5DXQXjee",
	"uc52Qzv0KBqBiodAQFDk7zlWywxCcI5Rp2CFizUa0tCdhOBoTRlZ6BLcfqQQzmL+q8DZurZWr5IAcDsv",
	"TaCOi+1mi83mzexAx3RlrWc6etbJZyy/Qby8L/eMDEnVYtnus942UKO9Ho22YO4/j6bMwnTRJ3NVHZjv",
	"q6LyAQraDpaeFptN8jYpRoWYB6fdOA0cY+sRLJ3CHbbbZSUY+7X++1S6QwjRCD3qFijOntJeiNIRbJTk",
	"4sfJm+k3In4SA3FQINF9d5OBqidhFDxmeXU4J16i7qIJXzcPnFZe8cRpGKSkrPLgHzGeZeAuKlxGH6oS",
	"lxtCbCFNWUbNYtb2ygj9Hg2rKr8UZxd9rBwrO6SaHIbiVOeX5B+JagGGl8Ubgz0ZR1IOqag1ruTNfTfm",
	"S+mgK9J3tlxslsMrhl0lFB/lyeSLq9P7R03KoTjO5+CG4sCkYUoOCOLKzUWul9K6GS1e2q95y3o8Y9Zk",
	"5hC5S0C5imOsFoIJJnJf/CSOwD3cl19hnXFPHKgO9WodjK7o1/PA6sXmwm0cA+HwWnXYXx1h/617l14B",
	"zrA9LGsKgYPlUFeOOFNop2vVDIAXVKpZ4/3N6tRcln8Khq5O/B/ygCxm4MEnz3Lw6BEDOJ/L7+SefC4G",
	"qYLNZfhB0aauwyQlgQ1XYxwyK65X5tH1K5iygvDfkH4ZipfYhnwgTuR31yGc/5tNOEBhNCpWpEHGClqz",
	"COfIA5rFwC5lg39Ggb1qwXSqX3QdlvqH4pSFmhmZe7ustH40P8EVSmuDlVxaVvW1Amfwpg9GrKOrPrla",
	"wIUuJFXMl5YTrmvCNIc1Y7SWlUWq5vPcnstz82X8XWg2S/Z1KygtLeCWmHjdEXy9DqS2JUNxgN7PF2IA",
	"MNQt4adiYCARkTfNmYTDXFQt3FI+YezGzW1nE4DPpYpnFK4X0laYZ8q39IMRSa9UHmAfjmLhdTubFbu9",
	"Xkfzx3QytGTqINVutU0wyTcOyVQvTvU0L4NOdffyRj3MUU20Uu6vwxgNxYlu3ZK7OqebupJkTiXA8c7k",
	"wDYaQmySpsXlF8oXlS+msaDBNtPbypPM1F016pIMqdDxdI2zqGiBLnTf7BLW459+Puuh7hPNYj+yiz5i",
	"IL/UiZnsytGbKwNs+e7Kw5pZiCHiOHe/R+4XlszQZ8BJI6cIqKywPsn2PAgukfYeoelvyUqZN2hnMlPX",
	"p/hVV0KJnXqdFjnUFetzfdu/D6ENlnPUvethVg06lF9fGVX/mrCEEWA/wukl3mz5Cfxp+SewEQVQyW8M",
	"lZZ1e09SVaoqOrGkkvTYFQzHJZF1u06INr3a1bj2mPXPch+LfkMl9EejaitRVeKGUSMuUwulrIt5EFYz",
	"boUH4d872zIR1NxS9Uzw4cUgTV2WjZm/hjREbtbB7A7cuxUiqRqUFGczNFSzN3+l5MJcTn8E46bUePmN",
	"l1uOOHRnWIm4/yfy7lzlI9QF1b44s4m6aDODqr8ygDICkdWk2Vx8j6zA0lppq7jH2JuCV7brQfGez9cY",
	"vY7dDxKn5VgzujVKHdTfZVcEbow3ZqtLmWQfjKpqEwtuRrWzqr75xPTE88t8EnYj6jAw3J+yxytBZ4Nx",
	"fc18qFskhuKkRfBS/yuswea7T1RCepe4DtE/BOHRmLfRjWu7jr3ql9za+ize8jvM+YzMiVc5lzTCS+oN",
	"z91k87a6Q72HfejwTU2rk6E4Juj1/gJUT33VF/+DP/Zykv/NgRMEwJnc08lw9ctFxo34uY4XxIwsNJsL",
	"NlkFTm/5HZJK56o1T8Rg1c9+vUhd1R6fRu5qAcENHOqrZjj8BM1euqvTPGlUo0gedyoi+rQkJio31+W3",
	"yNM76Cp5kLtOjrr5TLwEIsLGjarAfPqLS4WwZ9RpNh73WG+VXaarCJ/Mw18tOisQY9TK4wUd6q0HMa/d",
	"WbqnG3tsAv4GWkQQEh0GDWF8xYmxG27iD0sVTf2C8r/z+8oEiiRKyrCDqI8wOVIIJv9OVlAUfqOvHG7b",
	"1rtlc2HDFKoEBfAGYBqLkntpSVJ+I7/CqEptP68zsr2YQlSIxsZ/c6KZs9Wj0AybPaPNFJtJ5Fkta53z",
	"sNVoLCz+c71Zb9YXWs/CIOLblm1t0silj700gIt4HkNNq6TjY5AWuDCaQFirK2dD9BrzTR6az6rH7D8a",
	"df0bNarrqo56eRuZpo/yLEswKzUJmMrnxOPcd1kK3vgSrYnxrFpojC80ubYfbf9/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
